version: '3'

services:

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"

  backend:
    image: dheerajptdr/mean-backend:latest
    container_name: backend
    restart: always
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
    ports:
      - "3000:8080"

  frontend:
    image: dheerajptdr/mean-frontend:latest
    container_name: frontend
    restart: always
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
